version: '3'

services:
  # MySQL
  db:
    image: mysql:8.0.29
    container_name: foodie_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodie
      MYSQL_USER: makoto
      MYSQL_PASSWORD: makoto
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./db/mysql/data:/var/lib/mysql
    - ./db/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./db/mysql/ddl:/docker-entrypoint-initdb.d
    ports:
    - 3307:3307